grafana:
  enabled: true
  service:
    type: ClusterIP

alertmanager:
  enabled: true

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheus:
  service:
    type: ClusterIP
  prometheusSpec:
    retention: 6h
    scrapeInterval: 15s
    evaluationInterval: 15s
