apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: checkoutservice-memory-stress
  namespace: online-boutique
spec:
  mode: one
  selector:
    namespaces:
      - online-boutique
    labelSelectors:
      app: checkoutservice
  stressors:
    memory:
      workers: 1
      size: "80MB"
  duration: "60s"
