(function () {
  "use strict";

  const RECOVERY_SCENARIOS = {
    "cpu-stress": { label: "CPU Saturation", namespace: "online-boutique", deployment: "paymentservice", metric: "cpu", threshold: 80, incident_source: "chaos_mesh" },
    "memory-stress": { label: "Memory Saturation", namespace: "online-boutique", deployment: "checkoutservice", metric: "memory", threshold: 80, incident_source: "chaos_mesh" },
    "network-delay": { label: "Network Delay", namespace: "online-boutique", deployment: "paymentservice", metric: "latency", threshold: 0.1, incident_source: "chaos_mesh" },
    "pod-kill": { label: "Pod Failure", namespace: "online-boutique", deployment: "paymentservice", metric: "availability", threshold: 1, incident_source: "chaos_mesh" },
  };
  const AGENTS = {
    AIServiceHASupportAgent: { code: "HA", overviewId: "overview-agent-ha", pending: "Evidence 대기" },
    AIApplicationManagementAgent: { code: "APP", overviewId: "overview-agent-app", pending: "Evidence 대기" },
    AISemiconductorInfraOpsAgent: { code: "INF", overviewId: "overview-agent-inf", pending: "Evidence 대기" },
    CostOptimizationAgent: { code: "COST", overviewId: "overview-agent-cost", pending: "Evidence 대기" },
  };
  const MODE_BOUNDARIES = {
    mock: "Mock은 합성 Evidence를 사용하며 Kubernetes를 변경하지 않습니다.",
    "dry-run": "Dry-run은 실제 상태 또는 검증용 Snapshot을 사용하지만 Kubernetes를 변경하지 않습니다.",
    real: "Real은 실제 Kubernetes와 Prometheus를 사용하며 안전 검증 통과 후에만 복구 명령을 실행합니다.",
  };
  const STAGE_ORDER = [["preflight"],["injecting_fault","collecting_evidence"],["agent_reasoning"],["agent_reasoning"],["agent_reasoning"],["validating"],["executing"],["observing_recovery"],["analyzing","cleanup","completed"]];
  const STAGE_LABELS = { queued:"대기",preflight:"장애 조건 확인",injecting_fault:"장애 주입",collecting_evidence:"Evidence 수집",agent_reasoning:"Multi-Agent 판단",validating:"안전 명령 검증",executing:"복구 실행",observing_recovery:"복구 결과 확인",analyzing:"Recovery Evaluator Agent",cleanup:"정리",completed:"완료",failed:"실패",blocked:"안전 중단",cancelled:"취소됨",interrupted:"중단" };
  const TERMINAL = new Set(["completed","failed","blocked","cancelled","interrupted"]);
  const PLATFORM_VIEWS = new Set(["overview","experiment","agents","observability","aiopslab","analysis","history"]);
  const PRIMARY_VIEW_BY_PANEL = { overview:"overview",experiment:"experiment",agents:"experiment",observability:"experiment",aiopslab:"aiopslab",analysis:"analysis",history:"analysis" };
  const RESEARCH_DOCUMENTS = [["4-Agent 연구 보고서","docs/deliverables/AIOps_4Agent_Research_Report.docx"],["실험 실행 가이드","docs/deliverables/AIOps_Experiment_Operations_Guide.docx"],["Agent 정책 명세","docs/deliverables/AIOps_Agent_Policy_Specification.docx"]];
  const state = { activeView:"overview",scenarios:{...RECOVERY_SCENARIOS},selectedScenario:"cpu-stress",selectedMode:"mock",selectedAgent:"AIServiceHASupportAgent",connections:{},experimentId:"",job:null,events:[],eventSource:null,startedAt:null,timer:null,running:false,jobs:[],aiopslabCatalog:[],aiopslabRuntimeReady:false,aiopslabJobId:"",aiopslabJob:null,aiopslabEvents:[],aiopslabEventSource:null,comparisonRuntime:{},comparisonJobId:"",comparisonJob:null,comparisonEvents:[],comparisonEventSource:null };
  const $ = (id) => document.getElementById(id);
  const text = (id,value) => { const node=$(id); if(node) node.textContent=value; };
  const htmlEscape = (value) => String(value==null?"":value).replace(/[&<>"']/g,(ch)=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[ch]));

  async function api(path,options){ const response=await fetch(path,{headers:{"Content-Type":"application/json",...(options&&options.headers)},...options}); const contentType=response.headers.get("content-type")||""; const payload=contentType.includes("application/json")?await response.json():null; if(!response.ok) throw new Error(payload&&payload.detail?payload.detail:`요청 실패 (${response.status})`); return payload; }
  function scenario(){ return state.scenarios[state.selectedScenario]||RECOVERY_SCENARIOS["cpu-stress"]; }
  function modeLabel(mode){ return ({mock:"Mock","dry-run":"Dry-run",real:"Real"})[mode]||mode||"—"; }
  function jobStatusLabel(status){ return ({queued:"대기 중",running:"실행 중",cancelling:"취소 중",completed:"완료",failed:"실패",blocked:"안전 중단",cancelled:"취소됨",interrupted:"서버 재시작으로 중단"})[status]||status||"—"; }
  function stageLabel(stage){ return STAGE_LABELS[stage]||stage||"대기"; }
  function controllerLabel(controller,model){ return controller==="autogen"?`AutoGen Round-Robin${model?` · ${model}`:""}`:"Deterministic Mutual Supervision"; }
  function statusClass(status){ return ["completed","approved","success"].includes(status)?"success":["failed","blocked","safe_failure"].includes(status)?"danger":["running","cancelling"].includes(status)?"warning":"neutral"; }
  function formatNumber(value,digits=2){ return value==null||Number.isNaN(Number(value))?"—":Number(value).toFixed(digits); }
  function formatDate(value){ if(!value)return"—"; const date=new Date(value); return Number.isNaN(date.getTime())?"—":date.toLocaleString("ko-KR",{hour12:false}); }
  function actionLabel(action){ if(!action)return"—"; if(typeof action==="string")return action; if(!action.kind)return"—"; return action.replicas==null?action.kind:`${action.kind} → ${action.replicas}`; }
  function setBadge(id,label,kind){ const node=$(id); if(!node)return; node.textContent=label; node.className=node.className.replace(/\b(mock|dry-run|real|neutral|success|danger|warning)\b/g,"").trim(); node.classList.add(kind); }
  function setModeBadge(id,mode){ setBadge(id,mode==="dry-run"?"DRY-RUN":String(mode||"mock").toUpperCase(),mode||"mock"); }
  function setPressed(containerId,selector,selected,keyGetter){ const container=$(containerId); if(!container)return; container.querySelectorAll(selector).forEach((button)=>button.setAttribute("aria-pressed",String(keyGetter(button)===selected))); }

  function selectPlatformView(viewName,updateHash=true){ const resolved=PLATFORM_VIEWS.has(viewName)?viewName:"overview"; state.activeView=resolved; const primary=PRIMARY_VIEW_BY_PANEL[resolved]||"overview"; document.querySelectorAll("[data-view]").forEach((button)=>button.setAttribute("aria-pressed",String(button.dataset.view===primary))); document.querySelectorAll("[data-view-panel]").forEach((panel)=>{ const active=panel.dataset.viewPanel===resolved; panel.hidden=!active; panel.classList.toggle("is-active",active); }); document.querySelectorAll(".section-tabs [data-view-link]").forEach((button)=>button.setAttribute("aria-pressed",String(button.dataset.viewLink===resolved))); if(updateHash&&window.location.hash!==`#${resolved}`)window.location.hash=resolved; }
  function bindNavigation(){ document.querySelectorAll("[data-view]").forEach((button)=>button.addEventListener("click",()=>selectPlatformView(button.dataset.view))); document.querySelectorAll("[data-view-link]").forEach((button)=>button.addEventListener("click",()=>selectPlatformView(button.dataset.viewLink))); window.addEventListener("hashchange",()=>selectPlatformView(window.location.hash.slice(1),false)); selectPlatformView(window.location.hash.slice(1)||"overview",false); }

  function normalizeScenario(item){ const id=item.scenario_id||item.id; const fallback=RECOVERY_SCENARIOS[id]||{}; return {label:item.label||fallback.label||id,namespace:item.namespace||fallback.namespace,deployment:item.deployment||fallback.deployment,metric:item.metric||fallback.metric,threshold:item.threshold==null?fallback.threshold:item.threshold,incident_source:item.incident_source||fallback.incident_source||"chaos_mesh"}; }
  async function loadScenarios(){ try{ const payload=await api("/api/scenarios"); const resolved={}; (payload.scenarios||[]).forEach((item)=>{ const id=item.scenario_id||item.id; if(id&&id!=="aiopslab-hotel-reservation"&&(item.incident_source||"chaos_mesh")!=="aiopslab")resolved[id]=normalizeScenario(item); }); if(Object.keys(resolved).length)state.scenarios=resolved; }catch(_error){ state.scenarios={...RECOVERY_SCENARIOS}; } renderScenarioButtons(); syncOverviewScenarioOptions(); renderCondition(); }
  function renderScenarioButtons(){ const container=$("scenario-list"); if(!container)return; const buttons=Object.entries(state.scenarios).map(([id,item])=>{ const button=document.createElement("button"); button.type="button"; button.dataset.scenario=id; button.setAttribute("aria-pressed",String(id===state.selectedScenario)); const title=document.createElement("strong"); title.textContent=item.label; const meta=document.createElement("span"); meta.textContent=`Chaos Mesh · ${item.deployment} · ${item.metric}`; button.append(title,meta); button.addEventListener("click",()=>selectScenario(id)); return button; }); container.replaceChildren(...buttons); window.dispatchEvent(new CustomEvent("aiops:selection-updated")); }
  function syncOverviewScenarioOptions(){ const select=$("overview-scenario-select"); if(!select)return; select.replaceChildren(...Object.entries(state.scenarios).map(([id,item])=>{ const option=document.createElement("option"); option.value=id; option.textContent=item.label; return option; })); select.value=state.selectedScenario; }
  function selectScenario(id){ if(state.running||!state.scenarios[id])return; state.selectedScenario=id; setPressed("scenario-list","button[data-scenario]",id,(b)=>b.dataset.scenario); if($("overview-scenario-select"))$("overview-scenario-select").value=id; renderCondition(); resetEvidenceView(); window.dispatchEvent(new CustomEvent("aiops:selection-updated")); }
  function selectMode(mode){ if(state.running||!MODE_BOUNDARIES[mode])return; state.selectedMode=mode; setPressed("mode-control","button[data-mode]",mode,(b)=>b.dataset.mode); if($("overview-mode-select"))$("overview-mode-select").value=mode; text("mode-boundary",MODE_BOUNDARIES[mode]); text("overview-quick-help",MODE_BOUNDARIES[mode]); ["header-mode-badge","overview-mode-badge","experiment-mode-badge","selection-runtime-badge"].forEach((id)=>setModeBadge(id,mode)); renderSelectionSummary(); resetEvidenceView(); }
  function selectController(controller){ if(state.running)return; const resolved=controller==="autogen"?"autogen":"deterministic"; const autogen=state.connections.autogen||{ready:false,reason:"OpenAI API 키가 필요합니다"}; if(resolved==="autogen"&&!autogen.ready){ text("control-error",autogen.reason||"AutoGen runtime이 준비되지 않았습니다."); return; } $("controller-select").value=resolved; if($("overview-controller-select"))$("overview-controller-select").value=resolved; setPressed("controller-options","button[data-controller]",resolved,(b)=>b.dataset.controller); $("controller-model").hidden=resolved!=="autogen"; $("advanced-settings").open=resolved==="autogen"; $("profile-select").disabled=resolved==="autogen"; $("profile-select").value=resolved==="autogen"?"four-agent-autogen-v1":"four-agent-role-veto-v1"; text("controller-readiness",resolved==="autogen"?(autogen.reason||"AutoGen runtime 준비"):"Deterministic runtime 준비"); text("control-error",""); renderSelectionSummary(); }
  function ensureActionPolicyControl(){ const grid=document.querySelector(".advanced-settings-grid"); if(!grid||$("action-policy-select"))return; const label=document.createElement("label"); label.textContent="Action Policy"; const select=document.createElement("select"); select.id="action-policy-select"; select.innerHTML='<option value="baseline" selected>Baseline Policy</option><option value="learned">Learned Policy (advisory)</option>'; const note=document.createElement("small"); note.className="helper-text"; note.textContent="학습 정책은 기존 bounded action의 추천 순위만 바꾸며, 4-Agent 검토와 Validator를 우회하지 않습니다."; label.append(select,note); grid.append(label); }
  function controllerProfile(){ return $("controller-select").value==="autogen"?"four-agent-autogen-v1":$("profile-select").value; }
  function renderCondition(){ const item=scenario(); text("target-deployment",`${item.namespace} / ${item.deployment}`); text("target-metric",`${item.metric} · threshold ${item.threshold}`); text("evidence-scenario",item.label); text("evidence-target",`${item.namespace}/${item.deployment}`); text("observed-scenario",item.label); text("observed-target",`${item.namespace}/${item.deployment}`); text("observed-metric",`${item.metric} · threshold ${item.threshold}`); renderSelectionSummary(); renderGlobalContext(state.job); }
  function renderSelectionSummary(){ const item=scenario(); const controller=$("controller-select")?$("controller-select").value:"deterministic"; const model=controller==="autogen"&&$("model-input")?$("model-input").value.trim():""; text("selection-summary",`${item.label} · ${modeLabel(state.selectedMode)} · ${controllerLabel(controller,model)}`); }
  function evidenceBoundary(mode,actualSource){ if(actualSource)return actualSource; if(mode==="real")return"Kubernetes + Prometheus"; if(mode==="dry-run")return"Kubernetes Snapshot"; return"SyntheticEvidenceProvider"; }
  function incidentSource(mode){ return mode==="mock"?"Chaos Mesh Simulation":"Chaos Mesh"; }
  function resetEvidenceView(){ text("evidence-metric","실험 Evidence 수집 후 표시"); text("evidence-source",evidenceBoundary(state.selectedMode)); text("observed-incident-source",incidentSource(state.selectedMode)); text("observed-provider",evidenceBoundary(state.selectedMode)); text("observed-collected-at","수집되지 않음"); text("review-summary","역할별 의견 수집 대기"); text("consensus-summary","대기"); text("action-summary","선택 전"); text("consensus-status","Evidence 대기"); text("safety-status","검증 대기"); renderMetricCards({}); renderEvidenceComparison(null); renderAgentCards(null); renderInspector(); renderRecoveryReview(null); updateRecoveryPhase(null); }

  function reportFor(job=state.job){ const attempts=job&&job.result&&job.result.attempts; return Array.isArray(attempts)&&attempts.length?attempts[attempts.length-1].report||null:null; }
  function initialDecision(agent,report){ return report&&Array.isArray(report.initial_decisions)?report.initial_decisions.find((item)=>item.agent===agent)||null:null; }
  function reviewsBy(agent,report){ return report&&Array.isArray(report.peer_reviews)?report.peer_reviews.filter((item)=>item.reviewer===agent):[]; }
  function evaluationFor(report){ return report&&report.evaluation&&typeof report.evaluation==="object"?report.evaluation:null; }
  function evaluatorAgentReward(agent,report){ const evaluation=evaluationFor(report),rewards=evaluation&&evaluation.agent_rewards; const value=rewards&&rewards[agent]; return value==null||value===""||!Number.isFinite(Number(value))?null:Number(value); }
  function renderEvaluatorSummary(report){ const evaluation=evaluationFor(report)||{},components=evaluation.components||{},rewards=evaluation.agent_rewards||{}; text("detail-team-reward",evaluation.team_reward==null?"—":formatNumber(evaluation.team_reward,3)); text("detail-ha-reward",rewards.AIServiceHASupportAgent==null?"—":formatNumber(rewards.AIServiceHASupportAgent,3)); text("detail-app-reward",rewards.AIApplicationManagementAgent==null?"—":formatNumber(rewards.AIApplicationManagementAgent,3)); text("detail-infra-reward",rewards.AISemiconductorInfraOpsAgent==null?"—":formatNumber(rewards.AISemiconductorInfraOpsAgent,3)); text("detail-cost-reward",rewards.CostOptimizationAgent==null?"—":formatNumber(rewards.CostOptimizationAgent,3)); text("detail-outcome",components.outcome==null?"—":formatNumber(components.outcome,3)); text("detail-efficiency",components.efficiency==null?"—":formatNumber(components.efficiency,3)); text("detail-safety",components.safety==null?"—":formatNumber(components.safety,3)); text("detail-evidence-quality",components.evidence_quality==null?"—":formatNumber(components.evidence_quality,3)); text("detail-evaluator",evaluation.evaluator||"—"); text("detail-rubric",evaluation.rubric_version||"—"); text("detail-evaluation-reason",evaluation.reason||"Evaluator 결과가 없는 legacy report입니다."); }
  function renderAgentCards(report){ const grid=$("agent-grid"); if(grid)grid.querySelectorAll("button[data-agent]").forEach((button)=>{ const agent=button.dataset.agent,decision=initialDecision(agent,report),reviews=reviewsBy(agent,report),status=button.querySelector("small"); if(status)status.textContent=decision?(decision.proposed_action?actionLabel(decision.proposed_action):decision.reason||"판단 완료"):reviews.length?`${reviews.length}개 검토 · ${reviews[0].verdict||"완료"}`:AGENTS[agent].pending; }); Object.entries(AGENTS).forEach(([agent,info])=>{ const decision=initialDecision(agent,report),reviews=reviewsBy(agent,report); text(info.overviewId,decision?(decision.proposed_action?actionLabel(decision.proposed_action):decision.reason||"판단 완료"):reviews.length?`${reviews.length}개 검토`:info.pending); }); }
  function selectAgent(agent){ if(!AGENTS[agent])return; state.selectedAgent=agent; setPressed("agent-grid","button[data-agent]",agent,(b)=>b.dataset.agent); setPressed("agent-tabs","button[data-agent-tab]",agent,(b)=>b.dataset.agentTab); renderInspector(); }
  function renderInspector(){ const report=reportFor(),decision=initialDecision(state.selectedAgent,report),reviews=reviewsBy(state.selectedAgent,report); text("selected-agent",state.selectedAgent); text("agent-decision",decision?(decision.decision_type||"판단 완료"):reviews.length?"Peer review":"실험 Evidence 수집 후 표시"); text("agent-approval",decision?(decision.approved?"승인":"거부"):reviews.length?(reviews[0].verdict||"검토"):"대기"); const reward=evaluatorAgentReward(state.selectedAgent,report); text("agent-reward",reward==null?"—":formatNumber(reward,3)); text("controller-provenance",report?controllerLabel(report.controller||"deterministic",report.controller==="autogen"?report.model:""):"Deterministic Mutual Supervision"); text("agent-statement",decision?decision.reason||"판단 근거 없음":reviews[0]?reviews[0].reason||"검토 근거 없음":"실제 실행 결과의 Agent 판단 근거만 표시합니다."); const list=$("peer-reviews"); if(list)list.replaceChildren(...(reviews.length?reviews:[{verdict:"",reason:"상호검토 기록 대기"}]).map((review)=>{ const li=document.createElement("li"); li.textContent=`${review.verdict?`[${review.verdict}] `:""}${review.reason||"근거 없음"}`; return li; })); const panel=$("autogen-transcript-panel"); if(panel){ const isAutogen=report&&report.controller==="autogen"; panel.hidden=!isAutogen; if(isAutogen){ const lines=Array.isArray(report.autogen_transcript)?report.autogen_transcript:[]; $("autogen-transcript").replaceChildren(...(lines.length?lines:["AutoGen transcript가 기록되지 않았습니다."]).map((line)=>{ const li=document.createElement("li"); li.textContent=line; return li; })); } } }
  function updateRecoveryPhase(job){ const phase=!job?"design":TERMINAL.has(job.status)?"review":"observe"; document.querySelectorAll("[data-recovery-phase]").forEach((item)=>{ const active=item.dataset.recoveryPhase===phase; item.classList.toggle("is-active",active); item.classList.toggle("is-complete",phase==="review"&&item.dataset.recoveryPhase!=="review"); if(active)item.setAttribute("aria-current","step"); else item.removeAttribute("aria-current"); }); const live=$("live-workflow"),review=$("recovery-review-panel"); if(live)live.classList.toggle("is-current",phase==="observe"); if(review)review.classList.toggle("is-current",phase==="review"); }
  function renderRecoveryReview(report){ const recovery=report&&report.recovery_monitoring?report.recovery_monitoring:{},safeFailure=report&&report.final_status==="safe_failure",outcome=!report?"—":safeFailure?"안전 중단":recovery.recovery_success===true?"성공":recovery.recovery_success===false?"실패":report.final_status||"완료",kind=outcome==="성공"?"success":["실패","안전 중단"].includes(outcome)?"danger":"neutral",evaluation=evaluationFor(report),reward=evaluation&&evaluation.team_reward!=null?formatNumber(evaluation.team_reward,3):"—",before=report&&(report.evidence_before||(report.recovery_monitoring&&report.recovery_monitoring.before)),after=report&&(report.evidence_after||(report.recovery_monitoring&&report.recovery_monitoring.after)); text("recovery-review-outcome",outcome); text("recovery-review-action",report?actionLabel(report.selected_action):"—"); text("recovery-review-mttr",recovery.recovery_seconds==null?"—":`${formatNumber(recovery.recovery_seconds,2)}s`); text("recovery-review-reward",reward); text("recovery-review-evidence",before&&after?"복구 전·후 수집됨":"수집 대기"); text("recovery-review-note",!report?"실험을 실행하면 완료된 결과가 이 영역에 표시됩니다.":outcome==="성공"?"복구 결과와 Evaluator 기반 Reward가 기록되었습니다.":"실험 결과의 원인과 안전 검증 상태를 결과 상세에서 확인하세요."); setBadge("recovery-review-status",!report?"실행 전":outcome,kind); }
  function updateStage(stage,failed=false){ let index=STAGE_ORDER.findIndex((group)=>group.includes(stage)); if(index<0)index=0; [$("stage-timeline"),$("overview-stage-timeline")].filter(Boolean).forEach((timeline)=>timeline.querySelectorAll("li").forEach((item,itemIndex)=>{ item.classList.toggle("done",itemIndex<index||stage==="completed"); item.classList.toggle("active",itemIndex===index&&!failed&&stage!=="completed"); item.classList.toggle("failed",itemIndex===index&&failed); })); text("overview-current-stage",stageLabel(stage)); text("overview-completed-stages",`${stage==="completed"?9:Math.max(0,index)} / 9`); }
  function renderGlobalContext(job){ const request=job&&job.request?job.request:{},scenarioId=request.scenario_id||state.selectedScenario,item=state.scenarios[scenarioId]||RECOVERY_SCENARIOS[scenarioId]||scenario(),controller=request.controller||($("controller-select")?$("controller-select").value:"deterministic"),model=controller==="autogen"?request.model||"":"",stage=job&&job.current_stage?job.current_stage:"queued"; text("global-experiment-id",job&&job.experiment_id?job.experiment_id:"새 실험"); text("global-scenario",item?item.label:scenarioId); text("global-controller",controllerLabel(controller,model)); text("global-stage",stageLabel(stage)); text("job-status",job?jobStatusLabel(job.status):"대기"); text("experiment-id",job&&job.experiment_id?job.experiment_id:"새 실험"); }
  function renderMetricCards(metrics){ const container=$("observed-metrics"); if(!container)return; const aliases=[["CPU",["cpu","cpu_usage","cpu_percent"]],["Memory",["memory","memory_usage","memory_percent"]],["Latency",["latency","latency_seconds","p95_latency"]],["Error Rate",["error_rate","errors"]],["Desired Replicas",["desired_replicas"]],["Available Replicas",["available_replicas"]],["Restart Count",["restart_count","restarts"]],["Pod Status",["pod_status","status"]]]; container.replaceChildren(...aliases.map(([label,keys])=>{ const found=keys.find((key)=>Object.prototype.hasOwnProperty.call(metrics,key)),article=document.createElement("article"),span=document.createElement("span"),strong=document.createElement("strong"); span.textContent=label; strong.textContent=found?String(metrics[found]):"수집되지 않음"; article.append(span,strong); return article; })); }
  function renderEvidenceComparison(report){ const body=$("evidence-comparison-body"); if(!body)return; const before=report&&(report.evidence_before||(report.recovery_monitoring&&report.recovery_monitoring.before))||null,after=report&&(report.evidence_after||(report.recovery_monitoring&&report.recovery_monitoring.after))||null; if(!before||!after){ body.innerHTML='<tr><td colspan="4" class="empty-cell">복구 전후 Evidence가 수집되지 않았습니다.</td></tr>'; text("overview-evidence-change","수집되지 않음"); return; } const keys=Array.from(new Set([...Object.keys(before),...Object.keys(after)])).slice(0,12); body.innerHTML=keys.map((key)=>`<tr><td>${htmlEscape(key)}</td><td>${htmlEscape(before[key]??"수집되지 않음")}</td><td>${htmlEscape(after[key]??"수집되지 않음")}</td><td>${htmlEscape(before[key]===after[key]?"변화 없음":`${before[key]??"—"} → ${after[key]??"—"}`)}</td></tr>`).join(""); text("overview-evidence-change",keys.length?`${keys[0]}: ${before[keys[0]]??"—"} → ${after[keys[0]]??"—"}`:"수집되지 않음"); }
  function renderExperimentArtifacts(artifacts){ const container=$("experiment-artifacts"); if(!container)return; const links=Object.entries(artifacts||{}).filter(([,value])=>typeof value==="string"&&value).map(([name,value])=>{ const link=document.createElement("a"); link.href=value.startsWith("/")?value:`/api/artifacts/${value}`; link.target="_blank"; link.rel="noreferrer"; link.textContent=name; return link; }); container.replaceChildren(...(links.length?links:[Object.assign(document.createElement("span"),{textContent:"다운로드 가능한 Artifact 없음"})])); }
  function renderReport(report){ if(!report)return; const evidence=report.evidence||{},metrics=evidence.metric_values||{},metricEntries=Object.entries(metrics),mode=state.job&&state.job.request?state.job.request.mode:state.selectedMode,source=evidenceBoundary(mode,evidence.source); text("evidence-metric",metricEntries.length?metricEntries.map(([key,value])=>`${key} ${value}`).join(" · "):"수집 결과 없음"); text("evidence-source",source); text("observed-provider",source); text("observed-incident-source",incidentSource(mode)); text("observed-collected-at",evidence.collected_at?formatDate(evidence.collected_at):"수집되지 않음"); renderMetricCards(metrics); renderEvidenceComparison(report); const reviews=Array.isArray(report.peer_reviews)?report.peer_reviews:[],negotiation=report.negotiation||{}; text("review-summary",`${reviews.length}개 역할별 검토`); text("consensus-summary",negotiation.consensus||"미합의"); text("consensus-status",negotiation.consensus==="approved"?"합의 완료":"합의 확인 필요"); setBadge("overview-consensus-status",negotiation.consensus==="approved"?"합의 완료":"검토 필요",negotiation.consensus==="approved"?"success":"warning"); text("action-summary",actionLabel(report.selected_action)); text("overview-final-action",actionLabel(report.selected_action)); const safety=report.safety_validation||{}; text("allowlist-result",safety.valid===true?"통과":safety.valid===false?"차단":"대기"); text("validator-result",safety.valid===true?"VALID":safety.valid===false?"BLOCKED":"대기"); const cleanup=report.cleanup||{}; text("cleanup-result",cleanup.valid===false?"실패 · 검토 필요":cleanup.valid===true?"완료":"불필요/대기"); const recovery=report.recovery_monitoring||{},safeFailure=report.final_status==="safe_failure",recoveryLabel=safeFailure?"안전 중단":recovery.recovery_success===true?"성공":recovery.recovery_success===false?"실패":"—"; text("result-status",safeFailure?"안전 중단":report.final_status||"완료"); text("result-recovery",recoveryLabel); text("result-mttr",recovery.recovery_seconds==null?"—":`${formatNumber(recovery.recovery_seconds,2)}s`); text("overview-result-mttr",recovery.recovery_seconds==null?"—":`${formatNumber(recovery.recovery_seconds,2)}s`); text("overview-result-success",recoveryLabel); setBadge("overview-recovery-status",recoveryLabel==="성공"?"복구 성공":recoveryLabel==="안전 중단"?"안전 중단":recoveryLabel==="실패"?"복구 실패":"결과 없음",recoveryLabel==="성공"?"success":["실패","안전 중단"].includes(recoveryLabel)?"danger":"neutral"); const evaluation=evaluationFor(report),reward=evaluation&&evaluation.team_reward!=null?Number(evaluation.team_reward):null; text("result-reward",reward==null?"—":formatNumber(reward,3)); text("overview-result-reward",reward==null?"—":formatNumber(reward,3)); renderEvaluatorSummary(report); text("result-reviews",String(reviews.length)); const artifacts=report.artifacts||{}; text("result-artifacts",Object.keys(artifacts).length?`${Object.keys(artifacts).length}개`:"Job DB 저장"); renderExperimentArtifacts(artifacts); renderRecoveryReview(report); }

  function renderOverviewContext(job){
    text("overview-recent-scenario",scenario().label);
    text("overview-recent-controller",controllerLabel(job.request&&job.request.controller,job.request&&job.request.controller==="autogen"?job.request.model:""));
    text("overview-started-at",formatDate(job.started_at||job.created_at));
    text("overview-job-status",jobStatusLabel(job.status));
    setBadge("overview-progress-status",jobStatusLabel(job.status),statusClass(job.status));
    renderGlobalContext(job);
    renderCondition();
  }

  function renderOverviewStages(job){
    updateStage(job.current_stage,TERMINAL.has(job.status)&&job.status!=="completed");
  }

  function renderOverviewAgents(report){
    renderAgentCards(report);
    renderInspector();
    const postExecutionReviews=report&&Array.isArray(report.post_execution_reviews)?report.post_execution_reviews:[];
    postExecutionReviews.forEach((review)=>{
      const info=AGENTS[review.agent];
      const node=info&&$(info.overviewId);
      if(!node)return;
      const verdict=review.approved===true?"실행 후 승인":review.approved===false?"실행 후 재검토":"실행 후 확인";
      node.textContent=`${node.textContent} · ${verdict}`;
    });
  }

  function renderOverviewResult(report){
    renderReport(report);
  }

  function renderRecoveryRunStatus(job){
    const panel=$("recovery-run-status");
    if(!panel)return;
    const status=job&&job.status?job.status:"queued";
    const report=job?reportFor(job):null;
    const recovery=report&&report.recovery_monitoring?report.recovery_monitoring:{};
    const safeFailure=report&&report.final_status==="safe_failure";
    const recoveryLabel=safeFailure?"안전 중단":recovery.recovery_success===true?"성공":recovery.recovery_success===false?"실패":null;
    const terminal=Boolean(job&&TERMINAL.has(status));
    const visualStatus=recoveryLabel==="성공"?"success":recoveryLabel==="실패"||safeFailure?"danger":statusClass(status);
    const title=!job?"실행 대기":terminal&&recoveryLabel?`실험 ${recoveryLabel}`:`실험 ${jobStatusLabel(status)}`;
    let message="시나리오와 실행 모드를 선택한 뒤 실험을 실행하세요.";
    if(job){
      if(status==="queued")message="실험 Job이 실행 대기열에 등록되었습니다.";
      else if(status==="running")message="장애 주입, Evidence 수집, Agent 판단, 안전 검증과 복구 확인을 실행 중입니다.";
      else if(status==="completed"&&recoveryLabel==="성공")message="복구가 완료되었습니다. 결과 상세에서 Evidence와 Agent Reward를 확인하세요.";
      else if(status==="completed"&&recoveryLabel==="실패")message="실험은 종료되었지만 복구 결과가 실패로 기록되었습니다. 결과 상세에서 원인을 확인하세요.";
      else if(status==="completed")message="실험이 완료되었습니다. 결과 상세에서 실행 결과와 평가를 확인하세요.";
      else if(status==="blocked")message="안전 정책에 의해 실행이 중단되었습니다. 차단 사유를 확인하세요.";
      else if(status==="failed")message=job.error||"실험 중 오류가 발생했습니다. 로그와 이벤트를 확인하세요.";
      else if(status==="cancelled")message="실험이 취소되었습니다.";
      else if(status==="interrupted")message="서버 재시작으로 실험이 중단되었습니다.";
    }
    panel.className=`surface recovery-run-status ${visualStatus}`;
    const icon=$("recovery-run-status-icon");
    if(icon){ icon.className=`recovery-run-status-icon ${visualStatus}`; icon.textContent=visualStatus==="success"?"✓":visualStatus==="danger"?"!":status==="running"?"…":terminal?"—":"○"; }
    text("recovery-run-status-title",title);
    text("recovery-run-status-message",message);
    text("recovery-run-status-id",job&&job.experiment_id?`Experiment ID · ${job.experiment_id}`:"Experiment ID · —");
    const resultButton=$("recovery-view-result");
    if(resultButton)resultButton.hidden=!terminal;
  }

  function renderJob(job){
    state.job=job;
    state.experimentId=job.experiment_id;
    state.running=!TERMINAL.has(job.status);
    renderRecoveryRunStatus(job);
    updateRecoveryPhase(job);
    if(job.request){
      if(state.scenarios[job.request.scenario_id])state.selectedScenario=job.request.scenario_id;
      if(job.request.mode)state.selectedMode=job.request.mode;
      $("controller-select").value=job.request.controller||"deterministic";
      if($("model-input")&&job.request.model)$("model-input").value=job.request.model;
      if($("profile-select"))$("profile-select").value=job.request.protocol_profile||"four-agent-role-veto-v1";
      $("controller-model").hidden=job.request.controller!=="autogen";
      setPressed("scenario-list","button[data-scenario]",state.selectedScenario,(b)=>b.dataset.scenario);
      setPressed("mode-control","button[data-mode]",state.selectedMode,(b)=>b.dataset.mode);
      setPressed("controller-options","button[data-controller]",$("controller-select").value,(b)=>b.dataset.controller);
      if($("overview-scenario-select"))$("overview-scenario-select").value=state.selectedScenario;
      if($("overview-mode-select"))$("overview-mode-select").value=state.selectedMode;
      if($("overview-controller-select"))$("overview-controller-select").value=$("controller-select").value;
    }
    ["header-mode-badge","overview-mode-badge","experiment-mode-badge","selection-runtime-badge"].forEach((id)=>setModeBadge(id,state.selectedMode));
    const report=reportFor(job);
    renderOverviewContext(job);
    renderOverviewAgents(report);
    renderOverviewResult(report);
    renderOverviewStages(job);
    $("run-experiment").disabled=state.running||($("controller-select").value==="autogen"&&!(state.connections.autogen&&state.connections.autogen.ready));
    $("cancel-experiment").disabled=!state.running;
    if(TERMINAL.has(job.status))stopTimer();
    renderDetail(job);
    window.dispatchEvent(new CustomEvent("aiops:job-rendered"));
  }
  function addRuntimeEvent(event){ state.events.push(event); text("event-count",`${state.events.length} events`); const list=$("event-log"); if(list&&state.events.length===1)list.replaceChildren(); if(list){ const li=document.createElement("li"),time=document.createElement("time"),span=document.createElement("span"); time.textContent=new Date(event.created_at).toLocaleTimeString("ko-KR",{hour12:false}); span.textContent=`[${stageLabel(event.stage)}] ${event.message}`; li.append(time,span); list.append(li); } const overview=$("overview-event-log"); if(overview){ const latest=state.events.slice(-5); overview.replaceChildren(...latest.map((item)=>{ const li=document.createElement("li"); li.textContent=`${stageLabel(item.stage)} · ${item.message}`; return li; })); } updateStage(event.stage,event.status==="failed"); text("current-stage",event.stage); text("global-stage",stageLabel(event.stage)); }
  function connectEvents(){ closeEvents(); const stream=new EventSource(`/api/experiments/${state.experimentId}/events`); state.eventSource=stream; stream.addEventListener("runtime",(event)=>addRuntimeEvent(JSON.parse(event.data))); stream.addEventListener("job",async(event)=>{ const job=JSON.parse(event.data); closeEvents(); try{ renderJob(await api(`/api/experiments/${job.experiment_id}`)); await loadExperimentHistory(); }catch(error){showError(error);} }); stream.onerror=()=>{ if(!state.job||!TERMINAL.has(state.job.status))text("control-error","실시간 이벤트 연결을 재시도하고 있습니다."); }; }
  function closeEvents(){ if(state.eventSource)state.eventSource.close(); state.eventSource=null; }
  function startTimer(createdAt){ stopTimer(); state.startedAt=createdAt?new Date(createdAt):new Date(); const tick=()=>{ const seconds=Math.max(0,Math.floor((Date.now()-state.startedAt.getTime())/1000)); text("elapsed-time",`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`); }; tick(); state.timer=window.setInterval(tick,1000); }
  function stopTimer(){ if(state.timer)window.clearInterval(state.timer); state.timer=null; }
  function showError(error){ text("control-error",error instanceof Error?error.message:String(error)); }
  async function runExperiment(){ text("control-error",""); const item=scenario(),controller=$("controller-select").value; if(controller==="autogen"&&!(state.connections.autogen&&state.connections.autogen.ready)){ showError(new Error("AutoGen은 OpenAI API 키와 runtime 준비가 필요합니다.")); return; } const payload={scenario_id:state.selectedScenario,namespace:item.namespace,deployment:item.deployment,metric:item.metric,threshold:item.threshold,mode:state.selectedMode,backend:"python",protocol_profile:controllerProfile(),repetitions:Number($("repetitions-select").value),controller,model:controller === "autogen" ? $("model-input").value.trim() : "",incident_source:"chaos_mesh",benchmark_id:""}; if(state.selectedMode==="real"){ const confirmation=window.prompt("실제 Kubernetes 장애 주입과 복구를 실행하려면 EXECUTE REAL EXPERIMENT를 입력하세요."); if(confirmation!=="EXECUTE REAL EXPERIMENT")return; payload.real_confirmation="EXECUTE REAL EXPERIMENT"; } try{ const job=await api("/api/experiments",{method:"POST",body:JSON.stringify(payload)}); state.events=[]; $("event-log").replaceChildren(); renderJob(job); startTimer(job.created_at); connectEvents(); selectPlatformView("experiment"); }catch(error){ renderRecoveryRunStatus({status:"failed",error:error instanceof Error?error.message:String(error)}); showError(error);} }
  async function cancelExperiment(){ if(!state.experimentId)return; try{renderJob(await api(`/api/experiments/${state.experimentId}/cancel`,{method:"POST"}));}catch(error){showError(error);} }

  function normalizeConnectionKey(key){ return String(key||"").toLowerCase().replace(/[^a-z0-9]/g,""); }
  function connectionFor(connections,candidates){ const entries=Object.entries(connections||{}); for(const candidate of candidates){ const found=entries.find(([key])=>normalizeConnectionKey(key).includes(normalizeConnectionKey(candidate))); if(found)return found[1]; } return null; }
  function renderConnection(id,item,fallbackLabel){ const dot=$(`status-${id}`),label=$(`status-${id}-label`); if(!dot||!label)return; dot.className="status-dot"; if(!item){dot.classList.add("warning");label.textContent=fallbackLabel||"확인 필요";return;} if(item.ready){dot.classList.add("ready");const managed=item.port_forward&&item.port_forward.managed;label.textContent=id==="prometheus"&&managed?"자동 연결됨":"연결됨";dot.title=managed?"Control Plane이 Prometheus port-forward를 관리합니다.":"";} else{dot.classList.add(item.required_for_real?"error":"warning");label.textContent=item.reason&&/key|credential|api/i.test(item.reason)?"설정 필요":"미연결";} }
  async function loadConnections(){ try{ const payload=await api("/api/connections"),connections=payload.connections||{}; state.connections=connections; renderConnection("kubernetes",connectionFor(connections,["kubernetes","k8s"]),"확인 필요"); renderConnection("prometheus",connectionFor(connections,["prometheus"]),"확인 필요"); renderConnection("chaos-mesh",connectionFor(connections,["chaos","chaosmesh"]),"확인 필요"); renderConnection("aiopslab",connectionFor(connections,["aiopslab"]),"Benchmark 확인"); const autogen=connections.autogen||connectionFor(connections,["autogen"])||{ready:false,reason:"OpenAI API 키가 필요합니다"}; renderConnection("autogen",autogen,"설정 필요"); const required=Object.values(connections).filter((item)=>item.required_for_real),ready=required.filter((item)=>item.ready).length; text("connection-label",`${ready}/${required.length} Real 연결 준비`); $("connection-dot").classList.toggle("ready",required.length>0&&ready===required.length); text("autogen-controller-state",autogen.ready?"사용 가능":"사용 불가"); $("autogen-controller-state").classList.toggle("is-ready",Boolean(autogen.ready)); const autoButton=document.querySelector('[data-controller="autogen"]'); if(autoButton){ autoButton.disabled = !autogen.ready; autoButton.title=autogen.ready?"":(autogen.reason||"OpenAI API 키가 필요합니다"); } const overviewAuto=$("overview-controller-select")&&$("overview-controller-select").querySelector('option[value="autogen"]'); if(overviewAuto)overviewAuto.disabled=!autogen.ready; text("controller-readiness",autogen.reason||(autogen.ready?"AutoGen runtime 준비":"OpenAI API 키가 필요합니다")); }catch(_error){ ["kubernetes","prometheus","chaos-mesh","aiopslab","autogen"].forEach((id)=>renderConnection(id,null,"확인 실패")); text("connection-label","연결 정보 없음"); } }
  async function restoreLatestJob(){ try{ const payload=await api("/api/experiments?limit=20"),latest=payload.jobs&&payload.jobs[0]; if(!latest)return; const job=await api(`/api/experiments/${latest.experiment_id}`); renderJob(job); state.events=[]; $("event-log").replaceChildren(); (job.events||[]).forEach(addRuntimeEvent); if(!TERMINAL.has(job.status)){startTimer(job.started_at||job.created_at);connectEvents();} }catch(error){showError(error);} }

  function renderBenchmarkDescription(){ const select=$("aiopslab-benchmark-select"); if(!select)return; const benchmark=state.aiopslabCatalog.find((item)=>item.id===select.value); if(!benchmark){text("aiopslab-benchmark-description","선택 가능한 Benchmark가 없습니다.");return;} const pieces=[benchmark.description,benchmark.dataset?`Dataset: ${benchmark.dataset}`:"",benchmark.service?`Service: ${benchmark.service}`:"",benchmark.problem_id?`Problem: ${benchmark.problem_id}`:""].filter(Boolean); text("aiopslab-benchmark-description",pieces.join(" · ")||benchmark.title||benchmark.id); }
  async function loadAIOpsLabBenchmarks(){ try{ const payload=await api("/api/benchmarks/aiopslab"); state.aiopslabCatalog=payload.benchmarks||[]; state.aiopslabRuntimeReady=Boolean(payload.runtime&&payload.runtime.ready); const select=$("aiopslab-benchmark-select"); select.replaceChildren(...state.aiopslabCatalog.map((benchmark)=>{ const option=document.createElement("option"); option.value=benchmark.id; option.textContent=`${benchmark.title||benchmark.id}${benchmark.problem_id?` · ${benchmark.problem_id}`:""}`; return option; })); const reason=payload.runtime&&payload.runtime.reasons&&payload.runtime.reasons[0]; setBadge("aiopslab-runtime-status",state.aiopslabRuntimeReady?"실행 가능":"런타임 미준비",state.aiopslabRuntimeReady?"success":"warning"); $("aiopslab-run").disabled=!state.aiopslabRuntimeReady; $("aiopslab-run").title=state.aiopslabRuntimeReady?"":(reason||"런타임 미준비"); renderBenchmarkDescription(); renderConnection("aiopslab",{ready:state.aiopslabRuntimeReady,reason},"Benchmark 확인"); }catch(_error){ state.aiopslabRuntimeReady=false; setBadge("aiopslab-runtime-status","연결 실패","danger"); $("aiopslab-run").disabled=true; renderConnection("aiopslab",{ready:false},"연결 실패"); } }
  function renderAIOpsLabArtifacts(urls){ const container=$("aiopslab-artifacts"); if(!container)return; const labels={markdown:"요약 Markdown",csv:"결과 CSV"}; container.replaceChildren(...Object.entries(urls||{}).map(([name,href])=>{ const a=document.createElement("a"); a.href=href;a.target="_blank";a.rel="noreferrer";a.textContent=labels[name]||name;return a;})); }
  function renderAIOpsLabJob(job){ state.aiopslabJob=job;state.aiopslabJobId=job.job_id;const running=!TERMINAL.has(job.status),result=job.result||{};setBadge("aiopslab-job-status",jobStatusLabel(job.status),statusClass(job.status));$("aiopslab-run").disabled=running||!state.aiopslabRuntimeReady;$("aiopslab-cancel").disabled=!running;$("aiopslab-delete-current").disabled=!TERMINAL.has(job.status);setBadge("aiopslab-runtime-status",running?`${stageLabel(job.current_stage)} · 실행 중`:(state.aiopslabRuntimeReady?"실행 가능":"런타임 미준비"),running?"warning":state.aiopslabRuntimeReady?"success":"warning");text("aiopslab-accuracy",result.accuracy==null?"—":`${(Number(result.accuracy)*100).toFixed(1)}%`);text("aiopslab-ttd",result.average_ttd==null?"—":`${formatNumber(result.average_ttd,3)}s`);text("aiopslab-steps",result.average_steps==null?"—":formatNumber(result.average_steps,2));text("aiopslab-reward",result.average_final_reward==null?"—":formatNumber(result.average_final_reward,3));renderAIOpsLabArtifacts(job.artifact_urls||{});if(job.error)text("aiopslab-error",job.error);if(TERMINAL.has(job.status))closeAIOpsLabEvents(); }
  function addAIOpsLabEvent(event){ state.aiopslabEvents.push(event);text("aiopslab-event-count",`${state.aiopslabEvents.length} events`);const list=$("aiopslab-event-log");if(state.aiopslabEvents.length===1)list.replaceChildren();const li=document.createElement("li");li.textContent=`[${stageLabel(event.stage)}] ${event.message}${event.payload&&event.payload.repetition?` · ${event.payload.repetition}회차`:""}`;list.append(li); }
  function connectAIOpsLabEvents(){ closeAIOpsLabEvents();const stream=new EventSource(`/api/benchmarks/aiopslab/jobs/${state.aiopslabJobId}/events`);state.aiopslabEventSource=stream;stream.addEventListener("benchmark",(event)=>addAIOpsLabEvent(JSON.parse(event.data)));stream.addEventListener("job",async(event)=>{const summary=JSON.parse(event.data);closeAIOpsLabEvents();try{renderAIOpsLabJob(await api(`/api/benchmarks/aiopslab/jobs/${summary.job_id}`));}catch(error){text("aiopslab-error",error.message||String(error));}});stream.onerror=()=>{if(!state.aiopslabJob||!TERMINAL.has(state.aiopslabJob.status))text("aiopslab-error","Benchmark 이벤트 연결을 재시도하고 있습니다.");}; }
  function closeAIOpsLabEvents(){if(state.aiopslabEventSource)state.aiopslabEventSource.close();state.aiopslabEventSource=null;}
  async function runAIOpsLabBenchmark(){text("aiopslab-error","");if(!state.aiopslabRuntimeReady)return;try{const job=await api("/api/benchmarks/aiopslab/jobs",{method:"POST",body:JSON.stringify({benchmark_id:$("aiopslab-benchmark-select").value,repetitions:Number($("aiopslab-repetitions").value)})});state.aiopslabEvents=[];$("aiopslab-event-log").replaceChildren();renderAIOpsLabJob(job);connectAIOpsLabEvents();}catch(error){text("aiopslab-error",error.message||String(error));}}
  async function cancelAIOpsLabBenchmark(){if(!state.aiopslabJobId)return;try{renderAIOpsLabJob(await api(`/api/benchmarks/aiopslab/jobs/${state.aiopslabJobId}/cancel`,{method:"POST"}));}catch(error){text("aiopslab-error",error.message||String(error));}}
  async function deleteCurrentAIOpsLabJob(){if(!state.aiopslabJobId||!state.aiopslabJob||!TERMINAL.has(state.aiopslabJob.status))return;if(!window.confirm("현재 AIOpsLab Benchmark 결과와 산출물을 삭제할까요?"))return;try{await api(`/api/benchmarks/aiopslab/jobs/${state.aiopslabJobId}`,{method:"DELETE"});closeAIOpsLabEvents();state.aiopslabJobId="";state.aiopslabJob=null;state.aiopslabEvents=[];$("aiopslab-event-log")?.replaceChildren();$("aiopslab-artifacts")?.replaceChildren();$("aiopslab-delete-current").disabled=true;setBadge("aiopslab-job-status","결과 없음","neutral");text("aiopslab-error","");window.dispatchEvent(new CustomEvent("aiops:aiopslab-jobs-updated"));await restoreLatestAIOpsLabJob();}catch(error){text("aiopslab-error",error.message||String(error));}}
  async function deleteAllAIOpsLabJobs(){if(!window.confirm("종료된 AIOpsLab Benchmark 결과를 모두 삭제할까요?"))return;try{const result=await api("/api/benchmarks/aiopslab/jobs",{method:"DELETE"});closeAIOpsLabEvents();state.aiopslabJobId="";state.aiopslabJob=null;state.aiopslabEvents=[];$("aiopslab-event-log")?.replaceChildren();$("aiopslab-artifacts")?.replaceChildren();$("aiopslab-delete-current").disabled=true;setBadge("aiopslab-job-status",result.skipped_active_count?"실행 중 결과는 유지됨":"결과 없음","neutral");text("aiopslab-error",result.skipped_active_count?`${result.deleted_count}개 삭제 · ${result.skipped_active_count}개 실행 중이라 유지됨`:`${result.deleted_count}개 결과 삭제`);window.dispatchEvent(new CustomEvent("aiops:aiopslab-jobs-updated"));await restoreLatestAIOpsLabJob();}catch(error){text("aiopslab-error",error.message||String(error));}}
  async function restoreLatestAIOpsLabJob(){try{const payload=await api("/api/benchmarks/aiopslab/jobs?limit=20"),latest=payload.jobs&&payload.jobs[0];if(!latest)return;const job=await api(`/api/benchmarks/aiopslab/jobs/${latest.job_id}`);state.aiopslabEvents=[];$("aiopslab-event-log").replaceChildren();(job.events||[]).forEach(addAIOpsLabEvent);renderAIOpsLabJob(job);if(!TERMINAL.has(job.status))connectAIOpsLabEvents();}catch(_error){return;}}

  async function loadRecoveryComparison(){try{const payload=await api("/api/comparisons/recovery");state.comparisonRuntime=payload.runtime_modes||{};updateComparisonModeBoundary();}catch(_error){setBadge("comparison-runtime-status","연결 실패","danger");$("comparison-run").disabled=true;}}
  function updateComparisonModeBoundary(){const mode=$("comparison-mode").value,runtime=state.comparisonRuntime[mode]||{};text("comparison-boundary",mode==="real"?"Real은 Ubuntu에서 Chaos Mesh 장애를 실제 주입하고 Prometheus·Kubernetes 결과를 측정합니다. 서버 Gate와 확인 문구가 모두 필요합니다.":"Mock은 UI와 분석 파이프라인 검증용 합성 비교 데이터입니다. 실제 연구 근거와 구분해서 사용합니다.");setBadge("comparison-runtime-status",runtime.ready?`${modeLabel(mode)} 실행 가능`:"미준비",runtime.ready?"success":"warning");$("comparison-run").disabled=!runtime.ready;}
  function renderComparisonArtifacts(urls){const labels={outcomes_jsonl:"Outcomes JSONL",reward_markdown:"Reward 정책표",reward_csv:"Reward CSV",quantitative_markdown:"정량 요약",scenario_action_csv:"Scenario·Action CSV",policy_reward_csv:"정책 통계 CSV",success_rate_png:"성공률 PNG",recovery_seconds_png:"복구 시간 PNG",reward_policy_png:"Reward PNG"},container=$("comparison-artifacts");container.replaceChildren(...Object.entries(urls||{}).filter(([name])=>labels[name]).map(([name,href])=>{const a=document.createElement("a");a.href=href;a.target="_blank";a.rel="noreferrer";a.textContent=labels[name];return a;}));}
  function renderComparisonCharts(urls,version){[["comparison-success-chart",urls.success_rate_png],["comparison-recovery-chart",urls.recovery_seconds_png]].forEach(([id,href])=>{const img=$(id);if(href)img.src=`${href}?v=${encodeURIComponent(version||"latest")}`;else img.removeAttribute("src");});}
  function renderComparisonJob(job){state.comparisonJob=job;state.comparisonJobId=job.job_id;const running=!TERMINAL.has(job.status),result=job.result||{},overall=(result.statistics&&result.statistics.overall)||{},total=Number(result.total_treatments||(job.request&&job.request.repetitions*12)||0),completed=TERMINAL.has(job.status)?Number(result.total_treatments||0):Math.max(0,...state.comparisonEvents.map((event)=>Number(event.payload&&event.payload.completed_treatments||0)));text("comparison-job-status",jobStatusLabel(job.status));text("comparison-progress",`${completed} / ${total}`);text("comparison-success-rate",overall.success_rate==null?"—":`${(Number(overall.success_rate)*100).toFixed(1)}%`);text("comparison-mean-recovery",overall.mean_recovery_seconds==null?"—":`${formatNumber(overall.mean_recovery_seconds,2)}s`);text("comparison-evidence",result.evidence_type==="real_cluster"?"Real cluster":result.evidence_type==="synthetic_mock"?"합성 Mock":"—");$("comparison-run").disabled=running;$("comparison-cancel").disabled=!running;setBadge("comparison-runtime-status",running?`${stageLabel(job.current_stage)} · ${completed}/${total}`:jobStatusLabel(job.status),running?"warning":statusClass(job.status));renderComparisonArtifacts(job.artifact_urls||{});renderComparisonCharts(job.artifact_urls||{},job.updated_at);if(job.error)text("comparison-error",job.error);if(TERMINAL.has(job.status))closeComparisonEvents();}
  function addComparisonEvent(event){state.comparisonEvents.push(event);text("comparison-event-count",`${state.comparisonEvents.length} events`);const list=$("comparison-event-log");if(state.comparisonEvents.length===1)list.replaceChildren();const li=document.createElement("li"),payload=event.payload||{};li.textContent=`[${stageLabel(event.stage)}] ${event.message}${payload.total_treatments?` · ${payload.completed_treatments||0}/${payload.total_treatments}`:""}`;list.append(li);}
  function connectComparisonEvents(){closeComparisonEvents();const stream=new EventSource(`/api/comparisons/recovery/jobs/${state.comparisonJobId}/events`);state.comparisonEventSource=stream;stream.addEventListener("comparison",(event)=>addComparisonEvent(JSON.parse(event.data)));stream.addEventListener("job",async(event)=>{const summary=JSON.parse(event.data);closeComparisonEvents();try{renderComparisonJob(await api(`/api/comparisons/recovery/jobs/${summary.job_id}`));}catch(error){text("comparison-error",error.message||String(error));}});stream.onerror=()=>{if(!state.comparisonJob||!TERMINAL.has(state.comparisonJob.status))text("comparison-error","비교 실험 이벤트 연결을 재시도하고 있습니다.");};}
  function closeComparisonEvents(){if(state.comparisonEventSource)state.comparisonEventSource.close();state.comparisonEventSource=null;}
  async function runRecoveryComparison(){text("comparison-error","");const mode=$("comparison-mode").value;let confirmation="";if(mode==="real"){confirmation=window.prompt("실제 비교 실험을 실행하려면 EXECUTE REAL COMPARISON을 입력하세요.","")||"";if(confirmation!=="EXECUTE REAL COMPARISON")return;}try{const job=await api("/api/comparisons/recovery/jobs",{method:"POST",body:JSON.stringify({repetitions:Number($("comparison-repetitions").value),mode,guard_backend:$("comparison-guard").value,real_confirmation:confirmation})});state.comparisonEvents=[];$("comparison-event-log").replaceChildren();renderComparisonJob(job);connectComparisonEvents();}catch(error){text("comparison-error",error.message||String(error));}}
  async function cancelRecoveryComparison(){if(!state.comparisonJobId)return;try{renderComparisonJob(await api(`/api/comparisons/recovery/jobs/${state.comparisonJobId}/cancel`,{method:"POST"}));}catch(error){text("comparison-error",error.message||String(error));}}
  async function restoreLatestRecoveryComparison(){try{const payload=await api("/api/comparisons/recovery/jobs?limit=20"),latest=payload.jobs&&payload.jobs[0];if(!latest)return;const job=await api(`/api/comparisons/recovery/jobs/${latest.job_id}`);state.comparisonEvents=[];$("comparison-event-log").replaceChildren();(job.events||[]).forEach(addComparisonEvent);renderComparisonJob(job);if(!TERMINAL.has(job.status))connectComparisonEvents();}catch(_error){return;}}

  function reportMetrics(job){const report=reportFor(job),recovery=report&&report.recovery_monitoring||{},evaluation=evaluationFor(report);return{mttr:recovery.recovery_seconds,reward:evaluation&&evaluation.team_reward!=null?Number(evaluation.team_reward):null,success:recovery.recovery_success==null?undefined:recovery.recovery_success===true,finalStatus:report&&report.final_status,action:report&&report.selected_action};}
  function filteredJobs(){const period=$("history-period").value,scenarioId=$("history-scenario").value,controller=$("history-controller").value,mode=$("history-mode").value,status=$("history-status").value,search=$("history-search").value.trim().toLowerCase(),cutoff=period==="all"?null:Date.now()-Number(period)*86400000;return state.jobs.filter((job)=>{const request=job.request||{};if(cutoff&&new Date(job.created_at||0).getTime()<cutoff)return false;if(scenarioId!=="all"&&request.scenario_id!==scenarioId)return false;if(controller!=="all"&&request.controller!==controller)return false;if(mode!=="all"&&request.mode!==mode)return false;if(status!=="all"&&job.status!==status)return false;if(search&&!String(job.experiment_id||"").toLowerCase().includes(search))return false;return true;});}
  function ensureDeleteControls(){const historyPanel=document.querySelector('[data-result-panel="history"]');if(historyPanel&&!$("result-delete-status")){const status=document.createElement("p");status.id="result-delete-status";status.className="inline-status result-delete-status";status.setAttribute("aria-live","polite");status.hidden=true;(historyPanel.querySelector(".filter-bar")||historyPanel.firstElementChild)?.after(status);}const detailPanel=document.querySelector('[data-view-panel="history"]');if(detailPanel&&!$("detail-delete-button")){const button=document.createElement("button");button.id="detail-delete-button";button.type="button";button.className="destructive-action";button.textContent="실험 삭제";const header=detailPanel.querySelector(".detail-header,.page-heading");let actions=header&&header.querySelector(".detail-header-actions");if(!actions&&header){actions=document.createElement("div");actions.className="detail-header-actions";header.append(actions);}actions?.append(button);}}
  function setDeleteStatus(message,isError=false){const node=$("result-delete-status");if(!node)return;node.hidden=!message;node.textContent=message||"";node.classList.toggle("inline-error",Boolean(isError));}
  async function deleteExperimentResult(experimentId,{fromDetail=false}={}){const job=state.jobs.find((item)=>item.experiment_id===experimentId)||(state.job&&state.job.experiment_id===experimentId?state.job:null);if(job&&!TERMINAL.has(job.status)){setDeleteStatus("실행 중인 실험은 삭제할 수 없습니다.",true);return;}const confirmed=window.confirm("이 실험 결과를 삭제하시겠습니까?\nJob, 이벤트, 생성된 결과 파일이 영구적으로 삭제됩니다.");if(!confirmed)return;setDeleteStatus("실험 결과를 삭제하는 중입니다.");try{const result=await api(`/api/experiments/${encodeURIComponent(experimentId)}`,{method:"DELETE"});if(state.experimentId===experimentId){closeEvents();stopTimer();state.experimentId="";state.job=null;state.events=[];state.running=false;renderGlobalContext(null);}await loadExperimentHistory();setDeleteStatus(`${experimentId} 삭제 완료 · Artifact ${result&&result.artifacts_deleted!=null?result.artifacts_deleted:0}개 삭제`);if(fromDetail)selectPlatformView("analysis");}catch(error){const raw=error instanceof Error?error.message:String(error),message=/not terminal/i.test(raw)?"실행 중인 실험은 삭제할 수 없습니다.":raw;setDeleteStatus(message,true);}}
  function renderHistory(){const jobs=filteredJobs();text("history-count",`${jobs.length}건`);const body=$("experiment-history-body");if(!jobs.length){body.innerHTML='<tr><td colspan="9" class="empty-cell">조건에 맞는 실험 결과가 없습니다.</td></tr>';}else{body.replaceChildren(...jobs.map((job)=>{const request=job.request||{},item=state.scenarios[request.scenario_id]||RECOVERY_SCENARIOS[request.scenario_id]||{label:request.scenario_id||"—"},metrics=reportMetrics(job),tr=document.createElement("tr"),canDelete=TERMINAL.has(job.status);tr.innerHTML=`<td>${htmlEscape(job.experiment_id||"—")}</td><td>${htmlEscape(formatDate(job.created_at))}</td><td>${htmlEscape(item.label)}</td><td>${htmlEscape(controllerLabel(request.controller,request.controller==="autogen"?request.model:""))}</td><td><span class="mode-chip ${htmlEscape(request.mode||"mock")}">${htmlEscape(modeLabel(request.mode))}</span></td><td>${htmlEscape(metrics.finalStatus==="safe_failure"?"안전 중단":jobStatusLabel(job.status))}</td><td>${htmlEscape(metrics.mttr==null?"—":`${formatNumber(metrics.mttr,2)}s`)}</td><td>${htmlEscape(metrics.reward==null?"—":formatNumber(metrics.reward,3))}</td><td><div class="table-actions"><button type="button" class="table-action" data-history-detail>상세 보기</button><button type="button" class="table-action destructive" data-history-delete ${canDelete?"":"disabled"} title="${canDelete?"실험 결과 영구 삭제":"실행 중인 실험은 삭제할 수 없습니다."}">삭제</button></div></td>`;tr.querySelector("[data-history-detail]").addEventListener("click",async()=>{try{const detail=await api(`/api/experiments/${job.experiment_id}`);renderJob(detail);selectPlatformView("history");}catch(error){showError(error);}});tr.querySelector("[data-history-delete]").addEventListener("click",()=>deleteExperimentResult(job.experiment_id));return tr;}));} $("synthetic-warning").hidden=!jobs.some((job)=>(job.request&&job.request.mode)==="mock");renderDashboard();window.dispatchEvent(new CustomEvent("aiops:history-updated"));}
  async function loadExperimentHistory(){try{const payload=await api("/api/experiments?limit=100");state.jobs=payload.jobs||[];renderHistory();}catch(_error){$("experiment-history-body").innerHTML='<tr><td colspan="9" class="empty-cell">실험 이력을 불러오지 못했습니다.</td></tr>';window.dispatchEvent(new CustomEvent("aiops:history-updated"));}}
  function renderPerformanceDashboard(jobs){
    const validJobs=jobs.filter((job)=>reportFor(job));
    const average=(values,digits,suffix="")=>{
      const finite=values.filter((value)=>value!=null&&value!=="").map(Number).filter(Number.isFinite);
      return finite.length?`${(finite.reduce((sum,value)=>sum+value,0)/finite.length).toFixed(digits)}${suffix}`:"—";
    };
    const aggregate=(keyFor)=>{
      const groups=new Map();
      validJobs.forEach((job)=>{
        const key=keyFor(job);
        if(!key)return;
        const entry=groups.get(key)||{jobs:[],label:key};
        entry.jobs.push(job);
        groups.set(key,entry);
      });
      return Array.from(groups.values());
    };
    const cellsFor=(group)=>{
      const metrics=group.jobs.map(reportMetrics);
      const measured=metrics.filter((item)=>typeof item.success==="boolean");
      const successes=measured.filter((item)=>item.success).length;
      return {
        count:group.jobs.length,
        success:measured.length?`${((successes/measured.length)*100).toFixed(1)}%`:"—",
        mttr:average(metrics.map((item)=>item.mttr),2,"s"),
        reward:average(metrics.map((item)=>item.reward),3),
      };
    };
    const renderRows=(bodyId,groups,labelCells,colspan)=>{
      const body=$(bodyId);
      if(!body)return;
      if(!groups.length){body.innerHTML=`<tr><td colspan="${colspan}" class="empty-cell">집계 가능한 저장 결과가 없습니다.</td></tr>`;return;}
      body.replaceChildren(...groups.map((group)=>{
        const metrics=cellsFor(group),row=document.createElement("tr");
        row.innerHTML=`${labelCells(group).map((value)=>`<td>${htmlEscape(value)}</td>`).join("")}<td>${metrics.count}</td><td>${metrics.success}</td><td>${metrics.mttr}</td><td>${metrics.reward}</td>`;
        return row;
      }));
    };
    renderRows("dashboard-scenario-body",aggregate((job)=>{
      const id=job.request&&job.request.scenario_id;
      return (state.scenarios[id]||RECOVERY_SCENARIOS[id]||{}).label||id;
    }),(group)=>[group.label],5);
    renderRows("dashboard-action-body",aggregate((job)=>actionLabel(reportMetrics(job).action)),(group)=>[group.label],5);
    renderRows("dashboard-controller-body",aggregate((job)=>{
      const request=job.request||{};
      return `${controllerLabel(request.controller,request.controller==="autogen"?request.model:"")}|||${modeLabel(request.mode)}`;
    }),(group)=>group.label.split("|||"),6);
  }

  function renderDashboard(){
    const jobs=state.jobs;
    renderPerformanceDashboard(jobs);
    text("dashboard-total",String(jobs.length));
    const metrics=jobs.filter((job)=>reportFor(job)).map((job)=>reportMetrics(job));
    const completed=metrics.filter((item)=>typeof item.success==="boolean"),success=completed.filter((item)=>item.success).length;
    text("dashboard-success-rate",completed.length?`${((success/completed.length)*100).toFixed(1)}%`:"—");
    const mttrValues=metrics.map((item)=>Number(item.mttr)).filter(Number.isFinite);
    text("dashboard-mttr",mttrValues.length?`${(mttrValues.reduce((a,b)=>a+b,0)/mttrValues.length).toFixed(2)}s`:"—");
    const rewards=metrics.map((item)=>Number(item.reward)).filter(Number.isFinite);
    text("dashboard-reward",rewards.length?(rewards.reduce((a,b)=>a+b,0)/rewards.length).toFixed(3):"—");
    const distribution=jobs.reduce((acc,job)=>{const key=reportMetrics(job).finalStatus==="safe_failure"?"안전 중단":jobStatusLabel(job.status);acc[key]=(acc[key]||0)+1;return acc;},{}),container=$("dashboard-distribution");
    if(!jobs.length){container.innerHTML='<p class="empty-state">집계 가능한 실험 결과가 없습니다.</p>';return;}
    container.replaceChildren(...Object.entries(distribution).map(([label,count])=>{const row=document.createElement("div");row.className="distribution-row";row.innerHTML=`<span>${htmlEscape(label)}</span><div class="distribution-bar"><i style="width:${(count/jobs.length)*100}%"></i></div><strong>${count}</strong>`;return row;}));
  }
  function renderDetail(job){if(!job)return;const report=reportFor(job),request=job.request||{},detailScenario=state.scenarios[request.scenario_id]||RECOVERY_SCENARIOS[request.scenario_id]||{label:request.scenario_id||"—"};text("detail-experiment-subtitle",`${job.experiment_id} · ${detailScenario.label} · ${modeLabel(request.mode)} · ${controllerLabel(request.controller,request.controller==="autogen"?request.model:"")}`);const deleteButton=$("detail-delete-button");if(deleteButton){deleteButton.dataset.experimentId=job.experiment_id;deleteButton.disabled=!TERMINAL.has(job.status);deleteButton.title=deleteButton.disabled?"실행 중인 실험은 삭제할 수 없습니다.":"Job, 이벤트, Artifact 영구 삭제";}const timeline=$("detail-timeline"),events=job.events||state.events;timeline.replaceChildren(...(events.length?events.map((event)=>{const li=document.createElement("li");li.textContent=`${formatDate(event.created_at)} · ${stageLabel(event.stage)} · ${event.message}`;return li;}):[Object.assign(document.createElement("li"),{className:"empty-state",textContent:"타임라인 데이터가 없습니다."})]));const agentSummary=$("detail-agent-summary");agentSummary.replaceChildren(...Object.entries(AGENTS).map(([agent,info])=>{const decision=initialDecision(agent,report),reviews=reviewsBy(agent,report),evaluatorReward=evaluatorAgentReward(agent,report),article=document.createElement("article");article.innerHTML=`<span class="agent-code">${htmlEscape(info.code)}</span><div><strong>${htmlEscape(agent)}</strong><small>${decision?(decision.approved?"승인":"거부"):reviews.length?"Peer Review":"대기"} · Evaluator ${evaluatorReward==null?"—":formatNumber(evaluatorReward,3)}</small><p>${htmlEscape(decision?decision.reason||actionLabel(decision.proposed_action):reviews[0]?reviews[0].reason:"실행 결과 없음")}</p></div>`;return article;}));renderEvaluatorSummary(report);const evidence=report&&report.evidence;text("detail-evidence-summary",evidence?JSON.stringify(evidence,null,2):"Evidence가 없습니다.");text("detail-logs",report?JSON.stringify(report,null,2):"로그 데이터가 없습니다.");const detailEvents=$("detail-events");detailEvents.replaceChildren(...(events.length?events.map((event)=>{const li=document.createElement("li");li.textContent=`[${stageLabel(event.stage)}] ${event.message}`;return li;}):[Object.assign(document.createElement("li"),{className:"empty-state",textContent:"이벤트 데이터가 없습니다."})]));}
  function renderResearchDocuments(){const container=$("research-documents");if(!container)return;container.replaceChildren(...RESEARCH_DOCUMENTS.map(([label,path])=>{const a=document.createElement("a");a.href=`/api/artifacts/${path}`;a.target="_blank";a.rel="noreferrer";a.textContent=label;return a;}));}
  function bindTabs(){document.querySelectorAll("[data-result-tab]").forEach((button)=>button.addEventListener("click",()=>{document.querySelectorAll("[data-result-tab]").forEach((item)=>item.setAttribute("aria-pressed",String(item===button)));document.querySelectorAll("[data-result-panel]").forEach((panel)=>panel.hidden=panel.dataset.resultPanel!==button.dataset.resultTab);}));document.querySelectorAll("[data-detail-tab]").forEach((button)=>button.addEventListener("click",()=>{document.querySelectorAll("[data-detail-tab]").forEach((item)=>item.setAttribute("aria-pressed",String(item===button)));document.querySelectorAll("[data-detail-panel]").forEach((panel)=>panel.hidden=panel.dataset.detailPanel!==button.dataset.detailTab);}));}
  function bindControls(){ensureDeleteControls();bindNavigation();bindTabs();$("mode-control").querySelectorAll("button[data-mode]").forEach((button)=>button.addEventListener("click",()=>selectMode(button.dataset.mode)));$("controller-options").querySelectorAll("button[data-controller]").forEach((button)=>button.addEventListener("click",()=>selectController(button.dataset.controller)));$("agent-grid").querySelectorAll("button[data-agent]").forEach((button)=>button.addEventListener("click",()=>selectAgent(button.dataset.agent)));$("agent-tabs").querySelectorAll("button[data-agent-tab]").forEach((button)=>button.addEventListener("click",()=>selectAgent(button.dataset.agentTab)));$("run-experiment").addEventListener("click",runExperiment);$("cancel-experiment").addEventListener("click",cancelExperiment);$("overview-scenario-select").addEventListener("change",(event)=>selectScenario(event.target.value));$("overview-mode-select").addEventListener("change",(event)=>selectMode(event.target.value));$("overview-controller-select").addEventListener("change",(event)=>selectController(event.target.value));$("overview-run-experiment").addEventListener("click",runExperiment);$("aiopslab-benchmark-select").addEventListener("change",renderBenchmarkDescription);$("aiopslab-run").addEventListener("click",runAIOpsLabBenchmark);$("aiopslab-cancel").addEventListener("click",cancelAIOpsLabBenchmark);$("aiopslab-delete-current")?.addEventListener("click",deleteCurrentAIOpsLabJob);$("aiopslab-delete-all")?.addEventListener("click",deleteAllAIOpsLabJobs);$("comparison-mode").addEventListener("change",updateComparisonModeBoundary);$("comparison-run").addEventListener("click",runRecoveryComparison);$("comparison-cancel").addEventListener("click",cancelRecoveryComparison);["history-period","history-scenario","history-controller","history-mode","history-status"].forEach((id)=>$(id).addEventListener("change",renderHistory));$("history-search").addEventListener("input",renderHistory);$("detail-delete-button")?.addEventListener("click",()=>{const experimentId=$("detail-delete-button").dataset.experimentId||state.experimentId;if(experimentId)deleteExperimentResult(experimentId,{fromDetail:true});});}
  async function boot(){bindControls();renderResearchDocuments();renderScenarioButtons();renderCondition();resetEvidenceView();selectMode("mock");await Promise.all([loadScenarios(),loadConnections(),loadAIOpsLabBenchmarks(),loadRecoveryComparison(),loadExperimentHistory()]);await Promise.all([restoreLatestJob(),restoreLatestAIOpsLabJob(),restoreLatestRecoveryComparison()]);}
  window.addEventListener("beforeunload",()=>{closeEvents();closeAIOpsLabEvents();closeComparisonEvents();});
  boot();
  ensureActionPolicyControl();
  const researchFetch=window.fetch.bind(window);
  window.fetch=(input,options={})=>{const url=typeof input==="string"?input:input&&input.url;if(url&&url.endsWith("/api/experiments")&&options.body){try{const payload=JSON.parse(options.body);payload.action_policy=$("action-policy-select")?.value||"baseline";options={...options,body:JSON.stringify(payload)};}catch(_error){return researchFetch(input,options);}}return researchFetch(input,options);};
})();
